apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  username: YWRtaW4=                 # echo -n "admin" | base64
  password: c3VwZXJzZWNyZXQxMjM=    # echo -n "supersecret123" | base64
